'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,ShieldCheck,Sprout,Users,GraduationCap,Clock3,Heart,LockKeyhole,Save,Pencil,ImagePlus,FileText,CircleCheck,Send,RotateCcw} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {steps,validate,completion,displayValue,type Values,type Field} from './model';

type Props={english:boolean;verified:{name:string;dob:string;father:string;city:string;phone:string};relation:string;onDone:(percent:number)=>void;onCorrection:()=>void};
const chapters=[['તમારી ઓળખ','About you'],['સમાજ','Roots'],['જીવન અને પરિવાર','Your story'],['જન્મ','Birth'],['સમીક્ષા','Finish']];
const icons=[Sprout,Users,GraduationCap,Clock3,Heart];
export function GuidedBiodata({english,verified,relation,onDone,onCorrection}:Props){
 const t=(gu:string,en:string)=>english?en:gu;
 const [data,setData]=useState<Values>({gender:relation==='daughter'?'female':relation==='son'?'male':'',phone:verified.phone,contactKind:relation==='self'?'self':'father'});
 const [index,setIndex]=useState(0);const [ready,setReady]=useState(false);const [errors,setErrors]=useState<string[]>([]);const [resumed,setResumed]=useState(false);const [saved,setSaved]=useState(true);const [done,setDone]=useState(false);const [editing,setEditing]=useState(false);const [accurate,setAccurate]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);const step=steps[index];const Icon=icons[step.chapter];const key='samaj-setu:guided-bio:v1:'+encodeURIComponent(verified.dob+'|'+verified.phone);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const draft=JSON.parse(raw);if(draft.at>Date.now()-30*86400000&&draft.data&&typeof draft.data==='object'){const clean=Object.fromEntries(Object.entries(draft.data).filter(([k,v])=>typeof v==='string'&&k!=='__proto__'&&k!=='constructor'));setData(clean as Values);setIndex(Math.max(0,steps.findIndex(s=>s.id===draft.step)));setResumed(true);}}}catch{}setReady(true)},[key]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(key,JSON.stringify({data,step:step.id,at:Date.now()}));setSaved(true)}catch{setSaved(false)}},[data,step.id,key,ready]);
 function update(k:string,v:string){setData(d=>({...d,[k]:v}));setErrors(e=>e.filter(x=>x!==k));}
 function move(n:number){setIndex(n);setErrors([]);requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:'start',behavior:'smooth'})});}
 function next(){const invalid=validate(step,data);if(invalid.length){setErrors(invalid);return;}if(editing){setEditing(false);move(steps.length-1)}else move(Math.min(index+1,steps.length-1));}
 function edit(i:number){setEditing(true);move(i)}
 function submit(){const invalidStep=steps.findIndex(s=>validate(s,data).length>0);if(invalidStep!==-1){move(invalidStep);setErrors(validate(steps[invalidStep],data));return;}if(!accurate)return;setDone(true)}
 function sampleStep(){const samples:Values={gender:'male',height:'173',marital:'never',community:'surti',sect:'bhagat',surname:'Shah',mosal:'Mehta',education:'bachelor',degree:'B.Tech · Computer Engineering',work:'employed',role:'Software engineer',employer:'Sample company',mother:'Meena Shah',native:'Surat',diet:'vegetarian',brothers:'1',sisters:'0',birthplace:'Surat',birthtime:'10:30',rashi:'unknown',gan:'unknown',mangal:'unknown',contactKind:'father',phone:'9876543210'};setData(d=>({...d,...Object.fromEntries(step.fields.map(f=>[f.key,samples[f.key]||'']))}));setErrors([])}
 function field(f:Field){const value=data[f.key]||'';const invalid=errors.includes(f.key);const label=english?f.en:f.gu;const id='bio-'+f.key;const errorId=id+'-error';return <div className="bio-field" key={f.key}><label className="field-label" htmlFor={id}>{label}{f.required?<span className="required-dot"> *</span>:<small>{t('વૈકલ્પિક','Optional')}</small>}</label>{f.options&&f.options.length<=6?<RadioGroup value={value} onValueChange={v=>update(f.key,String(v))} className={`bio-choices ${f.options.length===2?'two':''}`} aria-label={label} aria-invalid={invalid} aria-describedby={invalid?errorId:undefined}>{f.options.map(([v,gu,en])=><label key={v} className={`bio-choice ${value===v?'selected':''}`}><RadioGroupItem value={v} aria-label={english?en:gu}/><span>{english?en:gu}</span>{value===v&&<Check size={15}/>}</label>)}</RadioGroup>:f.options?<Select value={value||null} onValueChange={v=>v&&update(f.key,v)}><SelectTrigger id={id} className="field-select" aria-label={label} aria-invalid={invalid}><SelectValue>{value?displayValue(f,value,english):t('પસંદ કરો','Choose an option')}</SelectValue></SelectTrigger><SelectContent>{f.options.map(([v,gu,en])=><SelectItem key={v} value={v}>{english?en:gu}</SelectItem>)}</SelectContent></Select>:<input id={id} className={`field ${invalid?'invalid':''}`} value={value} onChange={e=>update(f.key,e.target.value)} type={f.type==='number'?'number':f.type==='time'?'time':'text'} min={f.min} max={f.max} maxLength={f.key.toLowerCase().includes('phone')?10:150} inputMode={f.key.toLowerCase().includes('phone')?'numeric':undefined} aria-invalid={invalid} aria-describedby={invalid?errorId:undefined} disabled={f.key==='birthtime'&&data.birthUnknown==='yes'} placeholder={f.key==='height'?'173':f.key.toLowerCase().includes('phone')?'9876543210':undefined}/>}{f.hint&&<p className="field-hint">{t(...f.hint)}</p>}{invalid&&<p className="bio-error" id={errorId} role="alert">{f.type==='number'?t(`કૃપા કરીને ${f.min} થી ${f.max} વચ્ચે પૂર્ણાંક લખો.`,`Enter a whole number between ${f.min} and ${f.max}.`):f.key.toLowerCase().includes('phone')?t('10 અંકનો માન્ય મોબાઇલ નંબર લખો.','Enter a valid 10-digit mobile number.'):t('આ વિગત પૂર્ણ કરો અથવા યોગ્ય વિકલ્પ પસંદ કરો.','Complete this detail or choose an option.')}</p>}</div>}
 const basicRows=[[t('ઉમેદવાર','Candidate'),verified.name],[t('જન્મ તારીખ','Date of birth'),verified.dob],[t('પિતાનું નામ','Father’s name'),verified.father],[t('શહેર','City'),verified.city]];
 if(!ready)return <p className="sheet-copy">{t('ડ્રાફ્ટ ખોલી રહ્યા છીએ…','Opening your draft…')}</p>;
 if(done)return <div className="bio-finish"><div className="bio-success"><CircleCheck size={50} strokeWidth={1.3}/></div><span className="eyebrow gold">{t('એક સુંદર શરૂઆત','A THOUGHTFUL FIRST STEP')}</span><h2>{t('તમારો બાયોડેટા તૈયાર છે.','Your biodata is ready.')}</h2><p>{t('ડ્રાફ્ટ આ ઉપકરણ પર સાચવ્યો છે. પ્રોફાઇલ હજી પ્રકાશિત નથી.','Your draft is saved on this device. Your profile is not published.')}</p><div className="bio-next"><div><Check size={19}/><span>{t('વિગતો પૂર્ણ અને સમીક્ષા કરેલી','Details completed and reviewed')}</span></div><div><Clock3 size={19}/><span>{t('ઉમેદવારની અલગ સંમતિ બાકી','Separate candidate consent needed')}</span></div><div><ShieldCheck size={19}/><span>{t('ત્યારબાદ એડમિન બાયોડેટા મંજૂરી','Then admin biodata approval')}</span></div></div><p className="field-hint">{t('આ પ્રિવ્યૂ કોઈ સંમતિ વિનંતી મોકલતું નથી. માતા-પિતા ઉમેદવાર વતી સંમતિ આપી શકતા નથી.','This preview does not send a consent request. Parents cannot give consent on a candidate’s behalf.')}</p><button className="primary" onClick={()=>onDone(completion(data))}>{t('હોમ પર પાછા','Back to home')}<ArrowRight size={18}/></button><button className="text-button help-link" onClick={()=>setDone(false)}><Pencil size={16}/>{t('ફરી સમીક્ષા કરો','Review again')}</button></div>;
 return <div className="guided-bio">
  <div className="bio-progress-head"><span>{t('બાયોડેટા પૂર્ણ કરો','COMPLETE YOUR BIODATA')}</span><span>{index+1} / {steps.length}</span></div><Progress value={(index+1)/steps.length*100} aria-label={t('બાયોડેટા પ્રગતિ','Biodata progress')}/>
  <div className="bio-chapters">{chapters.map((c,i)=><span className={i===step.chapter?'current':i<step.chapter?'complete':''} key={c[1]}>{i<step.chapter?<Check size={12}/>:<i/>}{c[english?1:0]}</span>)}</div>
  {resumed&&<div className="bio-resume"><RotateCcw size={16}/><span>{t('સ્વાગત છે! જ્યાં અટક્યા હતા ત્યાંથી ચાલુ કરો.','Welcome back. Pick up where you left off.')}</span><button aria-label="Dismiss resume message" onClick={()=>setResumed(false)}>×</button></div>}
  <div className="bio-heading"><span className="bio-step-icon"><Icon size={25} strokeWidth={1.6}/></span><h2 ref={heading} tabIndex={-1}>{english?step.en:step.gu}</h2><p>{english?step.hintEn:step.hintGu}</p></div>
  <form onSubmit={e=>{e.preventDefault();index===steps.length-1?submit():next()}}>
   {step.id==='basics'&&<><div className="bio-verified"><span><ShieldCheck size={17}/>{t('નોંધણીમાંથી ભરેલું','Prefilled from registration')}</span><div className="detail-list">{basicRows.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div></div><button type="button" className="text-button" onClick={onCorrection}><Pencil size={15}/>{t('ચકાસેલી વિગતોમાં સુધારો માંગો','Request a change to verified details')}</button><div className="bio-reassurance"><Sprout size={20}/><p>{t('એક સમયે થોડા જવાબ. વચ્ચે અટકશો તો ડ્રાફ્ટ સાચવેલો રહેશે.','Just a few answers at a time. Take a break whenever you need.')}</p></div></>}
   {step.id==='mosal'&&<div className="bio-mosal"><Users size={25}/><b>{t('આ વિગત શા માટે જરૂરી છે?','Why does this matter?')}</b><p>{t('એક જ મોસાળ હોય તો સંબંધ માન્ય નથી. સાચું કુટુંબ લખવાથી અયોગ્ય સૂચનો ટાળી શકાય.','A shared mosal excludes a match. Naming the family accurately helps avoid unsuitable introductions.')}</p></div>}
   {step.fields.filter(f=>!((f.key==='role'||f.key==='employer')&&(data.work==='student'||data.work==='not_working'))).map(field)}
   {step.id==='birth'&&<label className="bio-check"><Checkbox checked={data.birthUnknown==='yes'} onCheckedChange={v=>{update('birthUnknown',v?'yes':'');if(v)update('birthtime','')}}/><span>{t('જન્મ સમયની જાણ નથી','I don’t know the birth time')}<small>{t('અજાણ્યો સમય હોય તો ચોક્કસ ગુણાંક નહીં બતાવાય.','Unknown time must not produce a precise compatibility score.')}</small></span></label>}
   {step.id==='media'&&<><button type="button" className={`bio-media ${data.photo?'added':''}`} onClick={()=>update('photo',data.photo?'':'sample')}><span><ImagePlus size={27}/></span><div><b>{data.photo?t('નમૂના ફોટો જોડ્યો','Sample photo added'):t('નમૂના ફોટો ઉમેરો','Add a sample photo')}</b><small>{t('આ પ્રિવ્યૂમાં ફક્ત નમૂના — કોઈ અપલોડ નહીં','Sample only in this preview — no upload')}</small></div>{data.photo?<Check size={20}/>:<ChevronRight size={20}/>}</button><div className="bio-photo-rule"><LockKeyhole size={18}/>{t('ફોટો ફક્ત તમારી મંજૂરી પછી જ દેખાશે.','Photos appear only after you approve the viewer.')}</div><button type="button" className={`bio-media ${data.kundali?'added':''}`} onClick={()=>update('kundali',data.kundali?'':'sample')}><span><FileText size={27}/></span><div><b>{data.kundali?t('નમૂના જન્માક્ષર જોડ્યાં','Sample janmakshar added'):t('જન્માક્ષર ઉમેરો','Add janmakshar')}</b><small>{t('વૈકલ્પિક · નમૂના દસ્તાવેજ','Optional · Sample document')}</small></div>{data.kundali?<Check size={20}/>:<ChevronRight size={20}/>}</button><label className="field-label">{t('જન્માક્ષર કોણ જોઈ શકે?','Who can view the janmakshar?')}</label><RadioGroup value={data.kundaliVisibility||'private'} onValueChange={v=>update('kundaliVisibility',String(v))} className="bio-choices two" aria-label="Janmakshar visibility">{[['private',t('ફક્ત હું','Only me')],['permission',t('મારી મંજૂરીથી','With my permission')]].map(([v,l])=><label className={`bio-choice ${(data.kundaliVisibility||'private')===v?'selected':''}`} key={v}><RadioGroupItem value={v}/><span>{l}</span></label>)}</RadioGroup></>}
   {step.id==='contact'&&verified.phone&&<button type="button" className="sample-link" onClick={()=>update('phone',verified.phone)}><ShieldCheck size={16}/>{t('ચકાસેલો લૉગ ઇન નંબર વાપરો','Use verified login number')}</button>}
   {step.id==='summary'&&<><div className="bio-summary-identity"><span className="avatar">{verified.name.charAt(0)}</span><div><h3>{verified.name}</h3><p>{verified.city} · {t('ખાનગી ડ્રાફ્ટ','Private draft')}</p></div><ShieldCheck size={23}/></div>{steps.slice(1,-1).map((s,i)=><section className="bio-summary" key={s.id}><div><h3>{english?s.en:s.gu}</h3><button type="button" aria-label={`Edit ${s.en}`} onClick={()=>edit(i+1)}><Pencil size={15}/>{t('સુધારો','Edit')}</button></div>{s.id==='media'?<p>{data.photo?t('નમૂના ફોટો · મંજૂરીથી','Sample photo · Permission required'):t('ફોટો ઉમેર્યો નથી','No photo added')}<br/>{data.kundali?t('નમૂના જન્માક્ષર','Sample janmakshar'):t('જન્માક્ષર ઉમેર્યાં નથી','No janmakshar added')}</p>:s.fields.map(f=><p key={f.key}><span>{english?f.en:f.gu}</span><b>{f.key==='birthtime'&&data.birthUnknown==='yes'?t('જાણ નથી','Not known'):displayValue(f,data[f.key]||'',english)||t('ઉમેર્યું નથી','Not added')}</b></p>)}</section>)}<label className="bio-check"><Checkbox checked={accurate} onCheckedChange={setAccurate}/><span>{t('મેં વિગતો ચકાસી છે અને તે મારી જાણ મુજબ સાચી છે.','I have reviewed these details and they are accurate to my knowledge.')}<small>{t('આ વિગતોની પુષ્ટિ છે, ઉમેદવારની પ્રકાશન સંમતિ નહીં.','This confirms accuracy, not candidate publication consent.')}</small></span></label><div className="bio-reassurance"><LockKeyhole size={21}/><p>{t('પ્રકાશન પહેલાં ઉમેદવારની અલગ સંમતિ અને એડમિન મંજૂરી જરૂરી છે.','Separate candidate consent and admin approval are required before publication.')}</p></div></>}
   <div className="bio-actions">{index<steps.length-1&&<p className="bio-next-label">{t('આગળ:','UP NEXT:')} <b>{english?steps[index+1].en:steps[index+1].gu}</b></p>}<div>{index>0&&<button type="button" className="bio-back" onClick={()=>move(index-1)} aria-label={t('પાછા','Back')}><ArrowLeft size={19}/></button>}<button type="submit" className="primary" disabled={index===steps.length-1&&!accurate}>{index===steps.length-1?t('ડ્રાફ્ટ પૂર્ણ કરો','Finish draft'):editing?t('સમીક્ષા પર પાછા','Back to review'):step.id==='basics'?t('મારો પરિચય શરૂ કરો','Let’s tell your story'):t('સાચવો અને આગળ વધો','Save & continue')}<ArrowRight size={18}/></button></div>{step.optional&&<button type="button" className="text-button" onClick={()=>{if(editing){setEditing(false);move(steps.length-1)}else move(index+1)}}>{t('હમણાં છોડો','Skip for now')}</button>}<button type="button" className="bio-save" onClick={()=>onDone(completion(data))}><Save size={15}/>{t('સાચવો અને પછી ચાલુ રાખો','Save & continue later')}</button><p className={`bio-autosave ${saved?'':'warning'}`} role="status">{saved?<Check size={13}/>:<Clock3 size={13}/>} {saved?t('ડ્રાફ્ટ આ ઉપકરણ પર સાચવ્યો','Draft saved on this device'):t('આ બ્રાઉઝરમાં સાચવી શકાતું નથી. પેજ બંધ ન કરો.','This browser cannot save the draft. Keep this page open.')}</p></div>
  </form>{step.fields.length>0&&<button className="bio-demo" onClick={sampleStep}>{t('આ પગલાં માટે નમૂના જવાબ ભરો','Fill sample answers for this step')}</button>}
 </div>
}
