export type Values = Record<string,string>;
export type Field = {key:string;gu:string;en:string;required?:boolean;type?:'text'|'number'|'time'|'select';options?:[string,string,string][];min?:number;max?:number;hint?:[string,string]};
export type Step = {id:string;gu:string;en:string;hintGu:string;hintEn:string;chapter:number;optional?:boolean;fields:Field[]};
const choice=(key:string,gu:string,en:string,options:[string,string,string][],required=false):Field=>({key,gu,en,options,required,type:'select'});
export const steps:Step[]=[
 {id:'basics',gu:'પહેલેથી થયેલો પરિચય.',en:'We already know a little.',hintGu:'ચકાસેલી વિગતો ફરી લખવાની જરૂર નથી.',hintEn:'No need to type your verified details again.',chapter:0,fields:[]},
 {id:'personal',gu:'તમારા વિશે થોડું.',en:'Start with the essentials.',hintGu:'થોડા સરળ જવાબથી સારી શરૂઆત.',hintEn:'A few simple answers to get started.',chapter:0,fields:[choice('gender','લિંગ','Gender',[['male','પુરુષ','Male'],['female','સ્ત્રી','Female']],true),{key:'height',gu:'ઊંચાઈ (સે.મી.)',en:'Height (cm)',type:'number',min:100,max:250,required:true},choice('marital','વૈવાહિક સ્થિતિ','Marital status',[['never','અપરિણીત','Never married'],['divorced','છૂટાછેડા થયેલ','Divorced'],['widowed','વિધુર / વિધવા','Widowed']],true)]},
 {id:'community',gu:'આપણા સમાજ સાથે જોડાણ.',en:'Your community roots.',hintGu:'પરિવારો માટે મહત્વની ઓળખ.',hintEn:'The details that help families understand your background.',chapter:1,fields:[choice('community','પેટા સમાજ','Sub-community',[['surti','સુરતી','Surti'],['khambhati','ખંભાતી','Khambhati'],['ahmedabadi','અમદાવાદી','Ahmedabadi'],['indori','ઇન્દોરી','Indori']],true),choice('sect','ભક્ત / જગત','Sect',[['bhagat','ભક્ત','Bhagat'],['jagat','જગત','Jagat']],true),{key:'surname',gu:'પિતૃપક્ષની અટક',en:'Paternal surname',required:true}]},
 {id:'mosal',gu:'તમારું મોસાળ કયું છે?',en:'Tell us about your mosal.',hintGu:'માતાના પિતાનું કુટુંબ — માતાનું હાલનું નામ નહીં.',hintEn:'Your maternal grandfather’s family, not your mother’s married name.',chapter:1,fields:[{key:'mosal',gu:'મોસાળનું કુટુંબ / અટક',en:'Maternal grandfather’s family / surname',required:true,hint:['ચોક્કસ ન હોય તો પરિવાર સાથે પુષ્ટિ કરો.','If unsure, confirm with your family.']} ]},
 {id:'education',gu:'અભ્યાસની સફર.',en:'Your learning journey.',hintGu:'સૌથી ઊંચી લાયકાત પસંદ કરો.',hintEn:'Choose your highest qualification.',chapter:2,fields:[choice('education','લાયકાત','Qualification',[['school','શાળા','School'],['diploma','ડિપ્લોમા','Diploma'],['bachelor','સ્નાતક','Bachelor’s'],['master','અનુસ્નાતક','Master’s'],['doctorate','ડૉક્ટરેટ','Doctorate'],['other','અન્ય','Other']],true),{key:'degree',gu:'ડિગ્રી / વિષય',en:'Degree / specialisation',hint:['જેમ કે B.Com, કમ્પ્યુટર એન્જિનિયરિંગ','For example B.Com, Computer Engineering']} ]},
 {id:'work',gu:'તમારું રોજિંદું કામ.',en:'What fills your day?',hintGu:'દરેક સફર અલગ હોય છે. તમારી હાલની સ્થિતિ પસંદ કરો.',hintEn:'Every journey is different. Choose what fits you today.',chapter:2,fields:[choice('work','હાલની સ્થિતિ','Current status',[['employed','નોકરી','Employed'],['business','વ્યવસાય','Business'],['student','વિદ્યાર્થી','Student'],['not_working','હાલ કામ નથી','Not working'],['other','અન્ય','Other']],true),{key:'role',gu:'વ્યવસાય / ભૂમિકા',en:'Profession / role'},{key:'employer',gu:'કંપની / વ્યવસાયનું નામ',en:'Employer / business name'}]},
 {id:'family',gu:'પરિવારનો પરિચય.',en:'The people behind your story.',hintGu:'તમારા પિતાનું નામ પહેલેથી ચકાસેલું છે.',hintEn:'Your father’s name is already in your verified details.',chapter:2,fields:[{key:'mother',gu:'માતાનું પૂરું નામ',en:'Mother’s full name'}, {key:'native',gu:'મૂળ વતન',en:'Native place'}]},
 {id:'lifestyle',gu:'થોડી વધુ ઓળખ.',en:'The little details.',hintGu:'આ વિગતો વૈકલ્પિક છે. પછી પણ ઉમેરી શકશો.',hintEn:'These details are optional. You can add them later.',chapter:2,optional:true,fields:[choice('diet','આહાર','Diet',[['vegetarian','શાકાહારી','Vegetarian'],['jain','જૈન','Jain'],['eggetarian','ઇંડા સહિત','Eggetarian'],['nonveg','માંસાહારી','Non-vegetarian'],['other','અન્ય','Other']]),{key:'brothers',gu:'ભાઈઓની સંખ્યા',en:'Number of brothers',type:'number',min:0,max:30},{key:'sisters',gu:'બહેનોની સંખ્યા',en:'Number of sisters',type:'number',min:0,max:30}]},
 {id:'birth',gu:'જન્મની વિગતો.',en:'A little about your birth.',hintGu:'જન્મ સમય ન જાણતા હો તો સ્પષ્ટ પસંદ કરો. અંદાજ જરૂરી નથી.',hintEn:'If you don’t know the time, say so. There’s no need to guess.',chapter:3,fields:[{key:'birthplace',gu:'જન્મ સ્થળ',en:'Birthplace'}, {key:'birthtime',gu:'જન્મ સમય',en:'Birth time',type:'time'}]},
 {id:'astro',gu:'પરિવારની જાણ મુજબ.',en:'As your family knows it.',hintGu:'આ આપેલી માહિતી છે, ગણતરી કરેલું પરિણામ નહીં.',hintEn:'These are declared details, not calculated results.',chapter:3,optional:true,fields:[choice('rashi','રાશિ','Rashi',[['unknown','જાણ નથી','Not known'],...['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'].map((x,i)=>[x,['મેષ','વૃષભ','મિથુન','કર્ક','સિંહ','કન્યા','તુલા','વૃશ્ચિક','ધનુ','મકર','કુંભ','મીન'][i],x] as [string,string,string])]),choice('gan','ગણ','Gan',[['unknown','જાણ નથી','Not known'],['dev','દેવ','Dev'],['manushya','મનુષ્ય','Manushya'],['rakshas','રાક્ષસ','Rakshas']]),choice('mangal','મંગળ સ્થિતિ','Mangal status',[['unknown','જાણ નથી','Not known'],['yes','મંગળ છે','Manglik'],['no','મંગળ નથી','Not Manglik']])]},
 {id:'media',gu:'તમારી ગોપનીયતા, તમારી પસંદ.',en:'Share on your terms.',hintGu:'ફોટા વૈકલ્પિક છે. જન્મ પ્રમાણપત્ર પ્રોફાઇલમાં ક્યારેય દેખાશે નહીં.',hintEn:'Photos are optional. Your birth certificate never appears on your profile.',chapter:4,optional:true,fields:[]},
 {id:'contact',gu:'પરિવારો કેવી રીતે જોડાય?',en:'Who should families contact?',hintGu:'બંને પરિવારોની સંમતિ પછી જ આ નંબર દેખાશે.',hintEn:'This number is revealed only after both families agree.',chapter:4,fields:[choice('contactKind','સંપર્ક વ્યક્તિ','Contact person',[['self','ઉમેદવાર','Candidate'],['father','પિતા','Father'],['mother','માતા','Mother'],['guardian','વાલી','Guardian']],true),{key:'phone',gu:'સંપર્ક નંબર',en:'Contact number',required:true},{key:'extraPhone',gu:'વધારાનો નંબર',en:'Additional number'}]},
 {id:'summary',gu:'તમારી કહાની, એક નજરમાં.',en:'Your story, at a glance.',hintGu:'મોકલતાં પહેલાં વિગતો ફરી જુઓ. કોઈપણ વિભાગ સુધારી શકશો.',hintEn:'Take one last look. You can edit any section before continuing.',chapter:4,fields:[]}
];
export function validate(step:Step,data:Values):string[]{
 const errors:string[]=[];
 for(const f of step.fields){const v=(data[f.key]||'').trim();if(f.required&&!v)errors.push(f.key);if(v&&f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<(f.min??0)||Number(v)>(f.max??999)||!Number.isInteger(Number(v))))errors.push(f.key);if(v&&f.options&&!f.options.some(o=>o[0]===v))errors.push(f.key);}
 if(step.id==='birth'&&data.birthUnknown!=='yes'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.birthtime||''))errors.push('birthtime');
 if(step.id==='contact'){if(!/^[6-9]\d{9}$/.test(data.phone||''))errors.push('phone');if(data.extraPhone&&!/^[6-9]\d{9}$/.test(data.extraPhone))errors.push('extraPhone');}
 return [...new Set(errors)];
}
export function completion(data:Values){const required=steps.flatMap(s=>s.fields.filter(f=>f.required));return Math.round(required.filter(f=>data[f.key]?.trim()).length/required.length*100);}
export function displayValue(f:Field,value:string,english:boolean){return f.options?.find(o=>o[0]===value)?.[english?2:1]||value;}
