// Generated by scripts/gen-db-types.mjs — do not edit by hand.
//
// Regenerate after every migration:
//   npm run db:verify && npm run db:types
//
// With the Supabase CLI available, prefer:
//   npx supabase gen types typescript --local > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      access_requests: {
        Row: {
          id: string;
          account_id: string;
          candidate_id: string;
          claimed_relationship: Database["public"]["Enums"]["relationship"];
          evidence_note: string | null;
          status: Database["public"]["Enums"]["access_request_status"];
          decided_at: string | null;
          decided_by_account_id: string | null;
          decision_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          candidate_id: string;
          claimed_relationship: Database["public"]["Enums"]["relationship"];
          evidence_note?: string | null;
          status?: Database["public"]["Enums"]["access_request_status"];
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          candidate_id?: string;
          claimed_relationship?: Database["public"]["Enums"]["relationship"];
          evidence_note?: string | null;
          status?: Database["public"]["Enums"]["access_request_status"];
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "access_requests_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "access_requests_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "access_requests_decided_by_account_id_fkey"; columns: ["decided_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      account_roles: {
        Row: {
          account_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by: string | null;
          granted_at: string;
          note: string | null;
        };
        Insert: {
          account_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          account_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [
          { foreignKeyName: "account_roles_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "account_roles_granted_by_fkey"; columns: ["granted_by"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      accounts: {
        Row: {
          id: string;
          phone: string;
          phone_verified_at: string | null;
          display_name: string | null;
          preferred_language: Database["public"]["Enums"]["language_code"];
          status: Database["public"]["Enums"]["account_status"];
          suspension_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          phone: string;
          phone_verified_at?: string | null;
          display_name?: string | null;
          preferred_language?: Database["public"]["Enums"]["language_code"];
          status?: Database["public"]["Enums"]["account_status"];
          suspension_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          phone_verified_at?: string | null;
          display_name?: string | null;
          preferred_language?: Database["public"]["Enums"]["language_code"];
          status?: Database["public"]["Enums"]["account_status"];
          suspension_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "accounts_id_fkey"; columns: ["id"]; isOneToOne: true; referencedRelation: "users"; referencedColumns: ["id"] },
        ];
      };
      app_settings: {
        Row: {
          id: boolean;
          review_target_hours: number;
          interest_expiry_days: number | null;
          photo_grant_days: number | null;
          share_link_days: number;
          consent_text_version: string;
          certificate_retention_days: number | null;
          updated_at: string;
          updated_by_account_id: string | null;
        };
        Insert: {
          id?: boolean;
          review_target_hours?: number;
          interest_expiry_days?: number | null;
          photo_grant_days?: number | null;
          share_link_days?: number;
          consent_text_version?: string;
          certificate_retention_days?: number | null;
          updated_at?: string;
          updated_by_account_id?: string | null;
        };
        Update: {
          id?: boolean;
          review_target_hours?: number;
          interest_expiry_days?: number | null;
          photo_grant_days?: number | null;
          share_link_days?: number;
          consent_text_version?: string;
          certificate_retention_days?: number | null;
          updated_at?: string;
          updated_by_account_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "app_settings_updated_by_fkey"; columns: ["updated_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      application_documents: {
        Row: {
          id: string;
          application_id: string;
          candidate_id: string;
          kind: string;
          bucket_id: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          checksum_sha256: string | null;
          uploaded_by_account_id: string | null;
          uploaded_at: string;
          retention_delete_after: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          application_id: string;
          candidate_id: string;
          kind?: string;
          bucket_id?: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          checksum_sha256?: string | null;
          uploaded_by_account_id?: string | null;
          uploaded_at?: string;
          retention_delete_after?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          application_id?: string;
          candidate_id?: string;
          kind?: string;
          bucket_id?: string;
          storage_path?: string;
          mime_type?: string;
          size_bytes?: number;
          checksum_sha256?: string | null;
          uploaded_by_account_id?: string | null;
          uploaded_at?: string;
          retention_delete_after?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "application_documents_application_id_fkey"; columns: ["application_id"]; isOneToOne: true; referencedRelation: "registration_applications"; referencedColumns: ["id"] },
          { foreignKeyName: "application_documents_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "application_documents_uploaded_by_account_id_fkey"; columns: ["uploaded_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      audit_events: {
        Row: {
          id: number;
          occurred_at: string;
          actor_account_id: string | null;
          actor_role: string | null;
          action: string;
          subject_table: string;
          subject_id: string | null;
          candidate_id: string | null;
          changes: Json;
        };
        Insert: {
          id?: number;
          occurred_at?: string;
          actor_account_id?: string | null;
          actor_role?: string | null;
          action: string;
          subject_table: string;
          subject_id?: string | null;
          candidate_id?: string | null;
          changes?: Json;
        };
        Update: {
          id?: number;
          occurred_at?: string;
          actor_account_id?: string | null;
          actor_role?: string | null;
          action?: string;
          subject_table?: string;
          subject_id?: string | null;
          candidate_id?: string | null;
          changes?: Json;
        };
        Relationships: [];
      };
      biodata_fields: {
        Row: {
          key: string;
          section: string;
          ordinal: number;
          label_gu: string;
          label_en: string;
          required: boolean;
          value_type: string;
          min_value: number | null;
          max_value: number | null;
          options: Json;
          affects_eligibility: boolean;
        };
        Insert: {
          key: string;
          section: string;
          ordinal: number;
          label_gu: string;
          label_en: string;
          required?: boolean;
          value_type: string;
          min_value?: number | null;
          max_value?: number | null;
          options?: Json;
          affects_eligibility?: boolean;
        };
        Update: {
          key?: string;
          section?: string;
          ordinal?: number;
          label_gu?: string;
          label_en?: string;
          required?: boolean;
          value_type?: string;
          min_value?: number | null;
          max_value?: number | null;
          options?: Json;
          affects_eligibility?: boolean;
        };
        Relationships: [];
      };
      biodata_revisions: {
        Row: {
          id: string;
          candidate_id: string;
          version: number;
          status: Database["public"]["Enums"]["revision_status"];
          data: Json;
          completion: number;
          source: string;
          unconfirmed_fields: string[];
          created_by_account_id: string | null;
          submitted_at: string | null;
          decided_at: string | null;
          decided_by_account_id: string | null;
          decision_reason: string | null;
          correction_fields: string[];
          approved_at: string | null;
          superseded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          version: number;
          status?: Database["public"]["Enums"]["revision_status"];
          data?: Json;
          completion?: number;
          source?: string;
          unconfirmed_fields?: string[];
          created_by_account_id?: string | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          correction_fields?: string[];
          approved_at?: string | null;
          superseded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          version?: number;
          status?: Database["public"]["Enums"]["revision_status"];
          data?: Json;
          completion?: number;
          source?: string;
          unconfirmed_fields?: string[];
          created_by_account_id?: string | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          correction_fields?: string[];
          approved_at?: string | null;
          superseded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "biodata_revisions_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "biodata_revisions_created_by_account_id_fkey"; columns: ["created_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "biodata_revisions_decided_by_account_id_fkey"; columns: ["decided_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_blocks: {
        Row: {
          id: string;
          blocker_candidate_id: string;
          blocked_candidate_id: string;
          created_by_account_id: string | null;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          blocker_candidate_id: string;
          blocked_candidate_id: string;
          created_by_account_id?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          blocker_candidate_id?: string;
          blocked_candidate_id?: string;
          created_by_account_id?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "candidate_blocks_blocked_candidate_id_fkey"; columns: ["blocked_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_blocks_blocker_candidate_id_fkey"; columns: ["blocker_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_blocks_created_by_account_id_fkey"; columns: ["created_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_community: {
        Row: {
          candidate_id: string;
          sub_community: string | null;
          sect: string | null;
          paternal_surname: string | null;
          paternal_surname_norm: string | null;
          mosal_family: string | null;
          mosal_family_norm: string | null;
          confirmed_at: string | null;
          confirmed_by_account_id: string | null;
          source: string;
          updated_at: string;
        };
        Insert: {
          candidate_id: string;
          sub_community?: string | null;
          sect?: string | null;
          paternal_surname?: string | null;
          mosal_family?: string | null;
          confirmed_at?: string | null;
          confirmed_by_account_id?: string | null;
          source?: string;
          updated_at?: string;
        };
        Update: {
          candidate_id?: string;
          sub_community?: string | null;
          sect?: string | null;
          paternal_surname?: string | null;
          mosal_family?: string | null;
          confirmed_at?: string | null;
          confirmed_by_account_id?: string | null;
          source?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "candidate_community_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_community_confirmed_by_account_id_fkey"; columns: ["confirmed_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_consents: {
        Row: {
          id: string;
          candidate_id: string;
          revision_id: string | null;
          granted_by_account_id: string;
          consent_text_version: string;
          granted_at: string;
          withdrawn_at: string | null;
          withdrawn_by_account_id: string | null;
          user_agent: string | null;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          revision_id?: string | null;
          granted_by_account_id: string;
          consent_text_version: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          withdrawn_by_account_id?: string | null;
          user_agent?: string | null;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          revision_id?: string | null;
          granted_by_account_id?: string;
          consent_text_version?: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          withdrawn_by_account_id?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          { foreignKeyName: "candidate_consents_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_consents_granted_by_account_id_fkey"; columns: ["granted_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_consents_revision_id_fkey"; columns: ["revision_id"]; isOneToOne: false; referencedRelation: "biodata_revisions"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_consents_withdrawn_by_account_id_fkey"; columns: ["withdrawn_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_contacts: {
        Row: {
          id: string;
          candidate_id: string;
          contact_kind: Database["public"]["Enums"]["contact_kind"];
          display_name: string | null;
          phone: string;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          contact_kind: Database["public"]["Enums"]["contact_kind"];
          display_name?: string | null;
          phone: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          contact_kind?: Database["public"]["Enums"]["contact_kind"];
          display_name?: string | null;
          phone?: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "candidate_contacts_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      candidate_media: {
        Row: {
          id: string;
          candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          bucket_id: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          is_primary: boolean;
          status: Database["public"]["Enums"]["media_status"];
          review_note: string | null;
          sort_order: number;
          uploaded_by_account_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          bucket_id: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          width?: number | null;
          height?: number | null;
          is_primary?: boolean;
          status?: Database["public"]["Enums"]["media_status"];
          review_note?: string | null;
          sort_order?: number;
          uploaded_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          kind?: Database["public"]["Enums"]["media_kind"];
          bucket_id?: string;
          storage_path?: string;
          mime_type?: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          is_primary?: boolean;
          status?: Database["public"]["Enums"]["media_status"];
          review_note?: string | null;
          sort_order?: number;
          uploaded_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "candidate_media_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_media_uploaded_by_account_id_fkey"; columns: ["uploaded_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_memberships: {
        Row: {
          id: string;
          candidate_id: string;
          account_id: string;
          role: Database["public"]["Enums"]["membership_role"];
          relationship: Database["public"]["Enums"]["relationship"];
          linked_by_account_id: string | null;
          linked_at: string;
          revoked_at: string | null;
          revoked_by_account_id: string | null;
          revoke_reason: string | null;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          account_id: string;
          role: Database["public"]["Enums"]["membership_role"];
          relationship: Database["public"]["Enums"]["relationship"];
          linked_by_account_id?: string | null;
          linked_at?: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
          revoke_reason?: string | null;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          account_id?: string;
          role?: Database["public"]["Enums"]["membership_role"];
          relationship?: Database["public"]["Enums"]["relationship"];
          linked_by_account_id?: string | null;
          linked_at?: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
          revoke_reason?: string | null;
        };
        Relationships: [
          { foreignKeyName: "candidate_memberships_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_memberships_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_memberships_linked_by_account_id_fkey"; columns: ["linked_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "candidate_memberships_revoked_by_account_id_fkey"; columns: ["revoked_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      candidate_privacy: {
        Row: {
          candidate_id: string;
          photo_visibility: Database["public"]["Enums"]["media_visibility"];
          kundali_visibility: Database["public"]["Enums"]["media_visibility"];
          reveal_contact_on_accept: boolean;
          updated_at: string;
        };
        Insert: {
          candidate_id: string;
          photo_visibility?: Database["public"]["Enums"]["media_visibility"];
          kundali_visibility?: Database["public"]["Enums"]["media_visibility"];
          reveal_contact_on_accept?: boolean;
          updated_at?: string;
        };
        Update: {
          candidate_id?: string;
          photo_visibility?: Database["public"]["Enums"]["media_visibility"];
          kundali_visibility?: Database["public"]["Enums"]["media_visibility"];
          reveal_contact_on_accept?: boolean;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "candidate_privacy_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      candidates: {
        Row: {
          id: string;
          public_code: string;
          full_name: string;
          full_name_norm: string | null;
          date_of_birth: string;
          gender: Database["public"]["Enums"]["gender"];
          father_name: string | null;
          father_name_norm: string | null;
          mother_name: string | null;
          city: string | null;
          native_place: string | null;
          identity_status: Database["public"]["Enums"]["identity_status"];
          publication_status: Database["public"]["Enums"]["publication_status"];
          published_revision_id: string | null;
          paused: boolean;
          match_found_at: string | null;
          deletion_requested_at: string | null;
          deleted_at: string | null;
          discoverable: boolean;
          created_by_account_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          public_code?: string;
          full_name: string;
          date_of_birth: string;
          gender: Database["public"]["Enums"]["gender"];
          father_name?: string | null;
          mother_name?: string | null;
          city?: string | null;
          native_place?: string | null;
          identity_status?: Database["public"]["Enums"]["identity_status"];
          publication_status?: Database["public"]["Enums"]["publication_status"];
          published_revision_id?: string | null;
          paused?: boolean;
          match_found_at?: string | null;
          deletion_requested_at?: string | null;
          deleted_at?: string | null;
          discoverable?: boolean;
          created_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          public_code?: string;
          full_name?: string;
          date_of_birth?: string;
          gender?: Database["public"]["Enums"]["gender"];
          father_name?: string | null;
          mother_name?: string | null;
          city?: string | null;
          native_place?: string | null;
          identity_status?: Database["public"]["Enums"]["identity_status"];
          publication_status?: Database["public"]["Enums"]["publication_status"];
          published_revision_id?: string | null;
          paused?: boolean;
          match_found_at?: string | null;
          deletion_requested_at?: string | null;
          deleted_at?: string | null;
          discoverable?: boolean;
          created_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "candidates_created_by_account_id_fkey"; columns: ["created_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "candidates_published_revision_fkey"; columns: ["published_revision_id"]; isOneToOne: false; referencedRelation: "biodata_revisions"; referencedColumns: ["id"] },
        ];
      };
      community_rules: {
        Row: {
          code: string;
          scope: Database["public"]["Enums"]["rule_scope"];
          title_gu: string;
          title_en: string;
          explanation_gu: string;
          explanation_en: string;
          enabled: boolean;
          definition: Json;
          ratified_at: string | null;
          ratified_by_account_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          code: string;
          scope: Database["public"]["Enums"]["rule_scope"];
          title_gu: string;
          title_en: string;
          explanation_gu: string;
          explanation_en: string;
          enabled?: boolean;
          definition?: Json;
          ratified_at?: string | null;
          ratified_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          scope?: Database["public"]["Enums"]["rule_scope"];
          title_gu?: string;
          title_en?: string;
          explanation_gu?: string;
          explanation_en?: string;
          enabled?: boolean;
          definition?: Json;
          ratified_at?: string | null;
          ratified_by_account_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "community_rules_ratified_by_account_id_fkey"; columns: ["ratified_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      contact_grants: {
        Row: {
          id: string;
          interest_id: string;
          candidate_low: string;
          candidate_high: string;
          granted_at: string;
          revoked_at: string | null;
          revoked_by_account_id: string | null;
        };
        Insert: {
          id?: string;
          interest_id: string;
          candidate_low: string;
          candidate_high: string;
          granted_at?: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
        };
        Update: {
          id?: string;
          interest_id?: string;
          candidate_low?: string;
          candidate_high?: string;
          granted_at?: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "contact_grants_candidate_high_fkey"; columns: ["candidate_high"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "contact_grants_candidate_low_fkey"; columns: ["candidate_low"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "contact_grants_interest_id_fkey"; columns: ["interest_id"]; isOneToOne: true; referencedRelation: "interests"; referencedColumns: ["id"] },
          { foreignKeyName: "contact_grants_revoked_by_account_id_fkey"; columns: ["revoked_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      duplicate_candidates: {
        Row: {
          id: string;
          application_id: string;
          candidate_id: string;
          matched_candidate_id: string;
          match_reasons: string[];
          similarity: number | null;
          status: Database["public"]["Enums"]["duplicate_status"];
          resolved_by_account_id: string | null;
          resolved_at: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          candidate_id: string;
          matched_candidate_id: string;
          match_reasons?: string[];
          similarity?: number | null;
          status?: Database["public"]["Enums"]["duplicate_status"];
          resolved_by_account_id?: string | null;
          resolved_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          candidate_id?: string;
          matched_candidate_id?: string;
          match_reasons?: string[];
          similarity?: number | null;
          status?: Database["public"]["Enums"]["duplicate_status"];
          resolved_by_account_id?: string | null;
          resolved_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "duplicate_candidates_application_id_fkey"; columns: ["application_id"]; isOneToOne: false; referencedRelation: "registration_applications"; referencedColumns: ["id"] },
          { foreignKeyName: "duplicate_candidates_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "duplicate_candidates_matched_candidate_id_fkey"; columns: ["matched_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "duplicate_candidates_resolved_by_account_id_fkey"; columns: ["resolved_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      family_preferences: {
        Row: {
          candidate_id: string;
          require_same_sub_community: boolean;
          require_same_sect: boolean;
          min_age: number | null;
          max_age: number | null;
          cities: string[];
          updated_at: string;
        };
        Insert: {
          candidate_id: string;
          require_same_sub_community?: boolean;
          require_same_sect?: boolean;
          min_age?: number | null;
          max_age?: number | null;
          cities?: string[];
          updated_at?: string;
        };
        Update: {
          candidate_id?: string;
          require_same_sub_community?: boolean;
          require_same_sect?: boolean;
          min_age?: number | null;
          max_age?: number | null;
          cities?: string[];
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "family_preferences_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      interests: {
        Row: {
          id: string;
          from_candidate_id: string;
          to_candidate_id: string;
          initiated_by_account_id: string | null;
          status: Database["public"]["Enums"]["interest_status"];
          message: string | null;
          expires_at: string | null;
          responded_at: string | null;
          responded_by_account_id: string | null;
          withdrawn_at: string | null;
          created_at: string;
          updated_at: string;
          pair_low: string | null;
          pair_high: string | null;
        };
        Insert: {
          id?: string;
          from_candidate_id: string;
          to_candidate_id: string;
          initiated_by_account_id?: string | null;
          status?: Database["public"]["Enums"]["interest_status"];
          message?: string | null;
          expires_at?: string | null;
          responded_at?: string | null;
          responded_by_account_id?: string | null;
          withdrawn_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          from_candidate_id?: string;
          to_candidate_id?: string;
          initiated_by_account_id?: string | null;
          status?: Database["public"]["Enums"]["interest_status"];
          message?: string | null;
          expires_at?: string | null;
          responded_at?: string | null;
          responded_by_account_id?: string | null;
          withdrawn_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "interests_from_candidate_id_fkey"; columns: ["from_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "interests_initiated_by_account_id_fkey"; columns: ["initiated_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "interests_responded_by_account_id_fkey"; columns: ["responded_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "interests_to_candidate_id_fkey"; columns: ["to_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      media_access_requests: {
        Row: {
          id: string;
          owner_candidate_id: string;
          viewer_candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          status: Database["public"]["Enums"]["media_request_status"];
          message: string | null;
          requested_by_account_id: string | null;
          created_at: string;
          decided_at: string | null;
          decided_by_account_id: string | null;
        };
        Insert: {
          id?: string;
          owner_candidate_id: string;
          viewer_candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          status?: Database["public"]["Enums"]["media_request_status"];
          message?: string | null;
          requested_by_account_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
        };
        Update: {
          id?: string;
          owner_candidate_id?: string;
          viewer_candidate_id?: string;
          kind?: Database["public"]["Enums"]["media_kind"];
          status?: Database["public"]["Enums"]["media_request_status"];
          message?: string | null;
          requested_by_account_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "media_access_requests_decided_by_account_id_fkey"; columns: ["decided_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "media_access_requests_owner_candidate_id_fkey"; columns: ["owner_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "media_access_requests_requested_by_account_id_fkey"; columns: ["requested_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "media_access_requests_viewer_candidate_id_fkey"; columns: ["viewer_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      media_grants: {
        Row: {
          id: string;
          owner_candidate_id: string;
          viewer_candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          request_id: string | null;
          granted_at: string;
          expires_at: string | null;
          revoked_at: string | null;
          revoked_by_account_id: string | null;
        };
        Insert: {
          id?: string;
          owner_candidate_id: string;
          viewer_candidate_id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          request_id?: string | null;
          granted_at?: string;
          expires_at?: string | null;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
        };
        Update: {
          id?: string;
          owner_candidate_id?: string;
          viewer_candidate_id?: string;
          kind?: Database["public"]["Enums"]["media_kind"];
          request_id?: string | null;
          granted_at?: string;
          expires_at?: string | null;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
        };
        Relationships: [
          { foreignKeyName: "media_grants_owner_candidate_id_fkey"; columns: ["owner_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "media_grants_request_id_fkey"; columns: ["request_id"]; isOneToOne: false; referencedRelation: "media_access_requests"; referencedColumns: ["id"] },
          { foreignKeyName: "media_grants_revoked_by_account_id_fkey"; columns: ["revoked_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "media_grants_viewer_candidate_id_fkey"; columns: ["viewer_candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      notification_outbox: {
        Row: {
          id: string;
          notification_id: string | null;
          channel: string;
          destination: string;
          template: string;
          variables: Json;
          status: string;
          attempts: number;
          last_error: string | null;
          created_at: string;
          sent_at: string | null;
        };
        Insert: {
          id?: string;
          notification_id?: string | null;
          channel: string;
          destination: string;
          template: string;
          variables?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Update: {
          id?: string;
          notification_id?: string | null;
          channel?: string;
          destination?: string;
          template?: string;
          variables?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "notification_outbox_notification_id_fkey"; columns: ["notification_id"]; isOneToOne: false; referencedRelation: "notifications"; referencedColumns: ["id"] },
        ];
      };
      notifications: {
        Row: {
          id: string;
          account_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          candidate_id: string | null;
          payload: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          candidate_id?: string | null;
          payload?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          candidate_id?: string | null;
          payload?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "notifications_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "notifications_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      registration_applications: {
        Row: {
          id: string;
          candidate_id: string;
          account_id: string;
          operator_relationship: Database["public"]["Enums"]["relationship"];
          status: Database["public"]["Enums"]["application_status"];
          declared: Json;
          submitted_at: string | null;
          review_due_at: string | null;
          review_target_hours: number;
          decided_at: string | null;
          decided_by_account_id: string | null;
          decision_reason: string | null;
          correction_fields: string[];
          resubmit_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          account_id: string;
          operator_relationship: Database["public"]["Enums"]["relationship"];
          status?: Database["public"]["Enums"]["application_status"];
          declared?: Json;
          submitted_at?: string | null;
          review_due_at?: string | null;
          review_target_hours?: number;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          correction_fields?: string[];
          resubmit_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          account_id?: string;
          operator_relationship?: Database["public"]["Enums"]["relationship"];
          status?: Database["public"]["Enums"]["application_status"];
          declared?: Json;
          submitted_at?: string | null;
          review_due_at?: string | null;
          review_target_hours?: number;
          decided_at?: string | null;
          decided_by_account_id?: string | null;
          decision_reason?: string | null;
          correction_fields?: string[];
          resubmit_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "registration_applications_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "registration_applications_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: true; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "registration_applications_decided_by_account_id_fkey"; columns: ["decided_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      review_claims: {
        Row: {
          subject_type: Database["public"]["Enums"]["review_subject"];
          subject_id: string;
          admin_account_id: string;
          claimed_at: string;
          expires_at: string;
        };
        Insert: {
          subject_type: Database["public"]["Enums"]["review_subject"];
          subject_id: string;
          admin_account_id: string;
          claimed_at?: string;
          expires_at: string;
        };
        Update: {
          subject_type?: Database["public"]["Enums"]["review_subject"];
          subject_id?: string;
          admin_account_id?: string;
          claimed_at?: string;
          expires_at?: string;
        };
        Relationships: [
          { foreignKeyName: "review_claims_admin_account_id_fkey"; columns: ["admin_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
      review_decisions: {
        Row: {
          id: string;
          subject_type: Database["public"]["Enums"]["review_subject"];
          subject_id: string;
          candidate_id: string | null;
          action: Database["public"]["Enums"]["review_action"];
          actor_account_id: string | null;
          actor_role: Database["public"]["Enums"]["app_role"] | null;
          from_status: string | null;
          to_status: string | null;
          fields: string[];
          reason_applicant: string | null;
          internal_note: string | null;
          revision_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_type: Database["public"]["Enums"]["review_subject"];
          subject_id: string;
          candidate_id?: string | null;
          action: Database["public"]["Enums"]["review_action"];
          actor_account_id?: string | null;
          actor_role?: Database["public"]["Enums"]["app_role"] | null;
          from_status?: string | null;
          to_status?: string | null;
          fields?: string[];
          reason_applicant?: string | null;
          internal_note?: string | null;
          revision_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_type?: Database["public"]["Enums"]["review_subject"];
          subject_id?: string;
          candidate_id?: string | null;
          action?: Database["public"]["Enums"]["review_action"];
          actor_account_id?: string | null;
          actor_role?: Database["public"]["Enums"]["app_role"] | null;
          from_status?: string | null;
          to_status?: string | null;
          fields?: string[];
          reason_applicant?: string | null;
          internal_note?: string | null;
          revision_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      revision_field_issues: {
        Row: {
          id: string;
          revision_id: string;
          field_key: string;
          message_gu: string;
          message_en: string;
          created_by_account_id: string | null;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          revision_id: string;
          field_key: string;
          message_gu: string;
          message_en: string;
          created_by_account_id?: string | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          revision_id?: string;
          field_key?: string;
          message_gu?: string;
          message_en?: string;
          created_by_account_id?: string | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "revision_field_issues_created_by_account_id_fkey"; columns: ["created_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "revision_field_issues_field_key_fkey"; columns: ["field_key"]; isOneToOne: false; referencedRelation: "biodata_fields"; referencedColumns: ["key"] },
          { foreignKeyName: "revision_field_issues_revision_id_fkey"; columns: ["revision_id"]; isOneToOne: false; referencedRelation: "biodata_revisions"; referencedColumns: ["id"] },
        ];
      };
      saved_profiles: {
        Row: {
          account_id: string;
          candidate_id: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          account_id: string;
          candidate_id: string;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          account_id?: string;
          candidate_id?: string;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "saved_profiles_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "saved_profiles_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
        ];
      };
      share_link_uses: {
        Row: {
          id: string;
          share_link_id: string;
          account_id: string | null;
          outcome: string;
          used_at: string;
        };
        Insert: {
          id?: string;
          share_link_id: string;
          account_id?: string | null;
          outcome: string;
          used_at?: string;
        };
        Update: {
          id?: string;
          share_link_id?: string;
          account_id?: string | null;
          outcome?: string;
          used_at?: string;
        };
        Relationships: [
          { foreignKeyName: "share_link_uses_account_id_fkey"; columns: ["account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "share_link_uses_share_link_id_fkey"; columns: ["share_link_id"]; isOneToOne: false; referencedRelation: "share_links"; referencedColumns: ["id"] },
        ];
      };
      share_links: {
        Row: {
          id: string;
          token_hash: string;
          candidate_id: string;
          created_by_account_id: string;
          created_at: string;
          expires_at: string;
          revoked_at: string | null;
          revoked_by_account_id: string | null;
          max_uses: number | null;
          use_count: number;
        };
        Insert: {
          id?: string;
          token_hash: string;
          candidate_id: string;
          created_by_account_id: string;
          created_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
          max_uses?: number | null;
          use_count?: number;
        };
        Update: {
          id?: string;
          token_hash?: string;
          candidate_id?: string;
          created_by_account_id?: string;
          created_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          revoked_by_account_id?: string | null;
          max_uses?: number | null;
          use_count?: number;
        };
        Relationships: [
          { foreignKeyName: "share_links_candidate_id_fkey"; columns: ["candidate_id"]; isOneToOne: false; referencedRelation: "candidates"; referencedColumns: ["id"] },
          { foreignKeyName: "share_links_created_by_account_id_fkey"; columns: ["created_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
          { foreignKeyName: "share_links_revoked_by_account_id_fkey"; columns: ["revoked_by_account_id"]; isOneToOne: false; referencedRelation: "accounts"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: {
      directory_profiles: {
        Row: {
          id: string | null;
          public_code: string | null;
          full_name: string | null;
          full_name_search: string | null;
          gender: Database["public"]["Enums"]["gender"] | null;
          city: string | null;
          native_place: string | null;
          age: number | null;
          sub_community: string | null;
          sect: string | null;
          paternal_surname: string | null;
          mosal_family: string | null;
          community_confirmed: boolean | null;
          biodata: Json | null;
          completion: number | null;
          revision_id: string | null;
          photo_visibility: Database["public"]["Enums"]["media_visibility"] | null;
          kundali_visibility: Database["public"]["Enums"]["media_visibility"] | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      admin_biodata_detail: {
        Args: {
          p_revision_id?: string;
        };
        Returns: Json;
      };
      admin_certificate_reference: {
        Args: {
          p_application_id?: string;
        };
        Returns: Json;
      };
      admin_claim_review: {
        Args: {
          p_subject?: Database["public"]["Enums"]["review_subject"];
          p_subject_id?: string;
        };
        Returns: Json;
      };
      admin_dashboard: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      admin_decide_access_request: {
        Args: {
          p_request_id?: string;
          p_approve?: boolean;
          p_reason?: string;
          p_role?: Database["public"]["Enums"]["membership_role"];
        };
        Returns: Json;
      };
      admin_decide_biodata: {
        Args: {
          p_revision_id?: string;
          p_action?: Database["public"]["Enums"]["review_action"];
          p_expected_status?: Database["public"]["Enums"]["revision_status"];
          p_reason?: string;
          p_issues?: Json;
          p_internal_note?: string;
        };
        Returns: Json;
      };
      admin_decide_media: {
        Args: {
          p_media_id?: string;
          p_approve?: boolean;
          p_note?: string;
        };
        Returns: undefined;
      };
      admin_decide_registration: {
        Args: {
          p_application_id?: string;
          p_action?: Database["public"]["Enums"]["review_action"];
          p_expected_status?: Database["public"]["Enums"]["application_status"];
          p_reason?: string;
          p_fields?: string[];
          p_internal_note?: string;
        };
        Returns: Json;
      };
      admin_member_detail: {
        Args: {
          p_candidate_id?: string;
        };
        Returns: Json;
      };
      admin_publication_queue: {
        Args: {
          p_statuses?: Database["public"]["Enums"]["revision_status"][];
          p_limit?: number;
          p_offset?: number;
        };
        Returns: { revision_id: string | null; candidate_id: string | null; public_code: string | null; full_name: string | null; version: number | null; status: Database["public"]["Enums"]["revision_status"] | null; completion: number | null; source: string | null; submitted_at: string | null; consent_active: boolean | null; unconfirmed: string[] | null; claimed_by: string | null }[];
      };
      admin_registration_detail: {
        Args: {
          p_application_id?: string;
        };
        Returns: Json;
      };
      admin_registration_queue: {
        Args: {
          p_statuses?: Database["public"]["Enums"]["application_status"][];
          p_query?: string;
          p_overdue?: boolean;
          p_limit?: number;
          p_offset?: number;
        };
        Returns: { application_id: string | null; candidate_id: string | null; public_code: string | null; full_name: string | null; date_of_birth: string | null; city: string | null; operator_phone: string | null; relationship: Database["public"]["Enums"]["relationship"] | null; status: Database["public"]["Enums"]["application_status"] | null; submitted_at: string | null; review_due_at: string | null; overdue: boolean | null; resubmit_count: number | null; has_certificate: boolean | null; open_duplicates: number | null; claimed_by: string | null }[];
      };
      admin_release_review: {
        Args: {
          p_subject?: Database["public"]["Enums"]["review_subject"];
          p_subject_id?: string;
        };
        Returns: undefined;
      };
      admin_resolve_duplicate: {
        Args: {
          p_id?: string;
          p_status?: Database["public"]["Enums"]["duplicate_status"];
          p_note?: string;
        };
        Returns: undefined;
      };
      admin_set_community_rule: {
        Args: {
          p_code?: string;
          p_enabled?: boolean;
          p_definition?: Json;
        };
        Returns: undefined;
      };
      admin_update_settings: {
        Args: {
          p_patch?: Json;
        };
        Returns: Database["public"]["Tables"]["app_settings"]["Row"];
      };
      attach_certificate: {
        Args: {
          p_application_id?: string;
          p_storage_path?: string;
          p_mime_type?: string;
          p_size_bytes?: number;
          p_checksum?: string;
        };
        Returns: string;
      };
      check_eligibility: {
        Args: {
          p_viewer?: string;
          p_target?: string;
        };
        Returns: Database["public"]["Enums"]["eligibility_verdict"];
      };
      confirm_biodata_fields: {
        Args: {
          p_revision_id?: string;
          p_fields?: string[];
        };
        Returns: Json;
      };
      confirm_community_details: {
        Args: {
          p_candidate_id?: string;
        };
        Returns: undefined;
      };
      create_share_link: {
        Args: {
          p_candidate_id?: string;
        };
        Returns: Json;
      };
      decide_media_access: {
        Args: {
          p_request_id?: string;
          p_approve?: boolean;
        };
        Returns: Json;
      };
      discover: {
        Args: {
          p_viewer_candidate?: string;
          p_query?: string;
          p_city?: string;
          p_sect?: string;
          p_sub_community?: string;
          p_saved_only?: boolean;
          p_limit?: number;
          p_offset?: number;
        };
        Returns: { id: string | null; public_code: string | null; full_name: string | null; age: number | null; city: string | null; sub_community: string | null; sect: string | null; mosal_family: string | null; biodata: Json | null; verdict: Database["public"]["Enums"]["eligibility_verdict"] | null; saved: boolean | null; interest_status: Database["public"]["Enums"]["interest_status"] | null; photo_visibility: Database["public"]["Enums"]["media_visibility"] | null; can_view_photos: boolean | null }[];
      };
      eligibility_explanation: {
        Args: {
          p_verdict?: Database["public"]["Enums"]["eligibility_verdict"];
        };
        Returns: { gu: string | null; en: string | null }[];
      };
      expire_stale_interests: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
      get_candidate_profile: {
        Args: {
          p_viewer_candidate?: string;
          p_target_candidate?: string;
        };
        Returns: Json;
      };
      grant_publication_consent: {
        Args: {
          p_candidate_id?: string;
        };
        Returns: Json;
      };
      grant_role: {
        Args: {
          p_account_id?: string;
          p_role?: Database["public"]["Enums"]["app_role"];
        };
        Returns: undefined;
      };
      list_interests: {
        Args: {
          p_candidate_id?: string;
          p_box?: string;
        };
        Returns: { id: string | null; status: Database["public"]["Enums"]["interest_status"] | null; outgoing: boolean | null; message: string | null; created_at: string | null; responded_at: string | null; counterpart_id: string | null; counterpart_code: string | null; counterpart_name: string | null; counterpart_age: number | null; counterpart_city: string | null; contact_visible: boolean | null }[];
      };
      list_saved: {
        Args: {
          p_viewer_candidate?: string;
        };
        Returns: { id: string | null; public_code: string | null; full_name: string | null; age: number | null; city: string | null; sub_community: string | null; sect: string | null; verdict: Database["public"]["Enums"]["eligibility_verdict"] | null; saved_at: string | null }[];
      };
      list_viewable_media: {
        Args: {
          p_viewer_candidate?: string;
          p_owner_candidate?: string;
          p_kind?: Database["public"]["Enums"]["media_kind"];
        };
        Returns: { id: string | null; bucket_id: string | null; storage_path: string | null; is_primary: boolean | null; sort_order: number | null }[];
      };
      my_context: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      register_media: {
        Args: {
          p_candidate_id?: string;
          p_kind?: Database["public"]["Enums"]["media_kind"];
          p_storage_path?: string;
          p_mime_type?: string;
          p_size_bytes?: number;
          p_is_primary?: boolean;
        };
        Returns: string;
      };
      request_candidate_access: {
        Args: {
          p_public_code?: string;
          p_relationship?: Database["public"]["Enums"]["relationship"];
          p_note?: string;
        };
        Returns: string;
      };
      request_identity_change: {
        Args: {
          p_candidate_id?: string;
          p_fields?: string[];
          p_reason?: string;
        };
        Returns: undefined;
      };
      request_media_access: {
        Args: {
          p_viewer_candidate?: string;
          p_owner_candidate?: string;
          p_kind?: Database["public"]["Enums"]["media_kind"];
          p_message?: string;
        };
        Returns: string;
      };
      resolve_share_link: {
        Args: {
          p_token?: string;
          p_viewer_candidate?: string;
        };
        Returns: Json;
      };
      respond_interest: {
        Args: {
          p_interest_id?: string;
          p_accept?: boolean;
        };
        Returns: Json;
      };
      revoke_media_grant: {
        Args: {
          p_grant_id?: string;
        };
        Returns: undefined;
      };
      revoke_role: {
        Args: {
          p_account_id?: string;
          p_role?: Database["public"]["Enums"]["app_role"];
        };
        Returns: undefined;
      };
      revoke_share_link: {
        Args: {
          p_id?: string;
        };
        Returns: undefined;
      };
      save_biodata_draft: {
        Args: {
          p_candidate_id?: string;
          p_data?: Json;
          p_source?: string;
        };
        Returns: Json;
      };
      send_interest: {
        Args: {
          p_from_candidate?: string;
          p_to_candidate?: string;
          p_message?: string;
        };
        Returns: string;
      };
      stage_imported_biodata: {
        Args: {
          p_candidate_id?: string;
          p_data?: Json;
        };
        Returns: Json;
      };
      start_registration: {
        Args: {
          p_relationship?: Database["public"]["Enums"]["relationship"];
          p_full_name?: string;
          p_date_of_birth?: string;
          p_gender?: Database["public"]["Enums"]["gender"];
          p_father_name?: string;
          p_mother_name?: string;
          p_city?: string;
          p_native_place?: string;
        };
        Returns: Json;
      };
      submit_biodata: {
        Args: {
          p_revision_id?: string;
        };
        Returns: Json;
      };
      submit_registration: {
        Args: {
          p_application_id?: string;
        };
        Returns: Json;
      };
      update_registration: {
        Args: {
          p_application_id?: string;
          p_full_name?: string;
          p_date_of_birth?: string;
          p_gender?: Database["public"]["Enums"]["gender"];
          p_father_name?: string;
          p_mother_name?: string;
          p_city?: string;
          p_native_place?: string;
        };
        Returns: undefined;
      };
      withdraw_interest: {
        Args: {
          p_interest_id?: string;
        };
        Returns: undefined;
      };
      withdraw_publication_consent: {
        Args: {
          p_candidate_id?: string;
        };
        Returns: Json;
      };
      withdraw_registration: {
        Args: {
          p_application_id?: string;
        };
        Returns: undefined;
      };
    };
    Enums: {
      access_request_status: "pending" | "approved" | "rejected" | "withdrawn";
      access_state: "signed_out" | "no_application" | "application_draft" | "awaiting_review" | "correction_requested" | "approved" | "rejected" | "suspended";
      account_status: "active" | "suspended" | "closed";
      app_role: "moderator" | "admin" | "superadmin";
      application_status: "draft" | "submitted" | "under_review" | "correction_requested" | "approved" | "rejected" | "withdrawn";
      contact_kind: "self" | "father" | "mother" | "guardian";
      duplicate_status: "open" | "confirmed" | "not_duplicate";
      eligibility_verdict: "eligible" | "insufficient_information" | "excluded_self" | "excluded_same_household" | "excluded_gender" | "excluded_shared_mosal" | "excluded_sub_community" | "excluded_sect" | "excluded_blocked" | "not_discoverable";
      gender: "male" | "female";
      identity_status: "unverified" | "pending" | "correction_requested" | "verified" | "rejected" | "suspended";
      interest_status: "pending" | "accepted" | "declined" | "withdrawn" | "expired";
      language_code: "gu" | "en";
      marital_status: "never_married" | "divorced" | "widowed";
      media_kind: "photo" | "kundali";
      media_request_status: "pending" | "approved" | "declined" | "withdrawn" | "revoked" | "expired";
      media_status: "pending_review" | "approved" | "rejected";
      media_visibility: "private" | "on_request" | "members";
      membership_role: "candidate" | "guardian" | "viewer";
      notification_kind: "registration_submitted" | "registration_decided" | "biodata_decided" | "access_request_decided" | "interest_received" | "interest_responded" | "photo_request_received" | "photo_request_decided" | "review_overdue";
      publication_status: "not_started" | "draft" | "in_review" | "correction_requested" | "published" | "unpublished" | "rejected";
      relationship: "self" | "son" | "daughter" | "brother" | "sister" | "ward" | "other";
      review_action: "approve" | "request_correction" | "reject" | "reopen" | "claim" | "release";
      review_subject: "registration" | "biodata_revision" | "access_request" | "duplicate" | "media";
      revision_status: "draft" | "submitted" | "under_review" | "correction_requested" | "approved" | "superseded" | "rejected";
      rule_scope: "universal" | "family_preference";
    };
    CompositeTypes: Record<PropertyKey, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
export type Fn<T extends keyof Database["public"]["Functions"]> =
  Database["public"]["Functions"][T];
